package bit.com.theaters.model;

import java.io.Serializable;

/*

DROP TABLE THEATERS_TICKET 
CASCADE CONSTRAINTS;

DROP SEQUENCE THEATERS_TICKET_SEQ; 


CREATE TABLE THEATERS_TICKET (
    TICKET_NUM NUMBER(5) PRIMARY KEY,
    TICKET_TITLE VARCHAR2(100) NOT NULL,
    TICKET_DATE VARCHAR2(10) NOT NULL,
    TICKET_TIME VARCHAR2(5) NOT NULL,
    TICKET_PLACE VARCHAR2(10) NOT NULL,
    USER_ID VARCHAR2(50) NOT NULL,
    TICKET_AUTH NUMBER(1) NOT NULL
);
   
CREATE SEQUENCE THEATERS_TICKET_SEQ
START WITH 10000
INCREMENT BY 1
MAXVALUE 19999
NOCYCLE;


ALTER TABLE THEATERS_TICKET
    ADD CONSTRAINT FK_TICKET_USER_ID_USERS FOREIGN KEY (USER_ID)
        REFERENCES THEATERS_USERS (USER_ID);

 
 */



public class TicketDto implements Serializable {

}
